apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: ACME-EMAIL
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            email: CLOUDFLARE-EMAIL
            apiKeySecretRef:
              name: cloudflare-apikey-secret
              key: apikey.txt
        selector:
          dnsZones:
            - "norseamerican.com"
